import React, { useEffect, useRef } from 'react';
import { Card, Flag, SkillBar, StepHeader, BtnPrimary, BtnGhost } from '../components/ui';

const EVAL_METRICS = [
  { name: 'Correctness',        val: 90, color: 'var(--green)' },
  { name: 'Edge case handling', val: 85, color: 'var(--green)' },
  { name: 'Code efficiency',    val: 70, color: 'var(--amber)' },
  { name: 'Pandas idiom usage', val: 65, color: 'var(--amber)' },
  { name: 'Robustness',         val: 40, color: 'var(--red)'   },
];

const BEHAVIOUR_FLAGS = [
  { text: '4 rewrites of label-map logic',              variant: 'warn' },
  { text: '11 min time-to-first-line (high hesitation)', variant: 'warn' },
  { text: '2 tab-switches detected (likely Googled .map syntax)', variant: 'bad' },
  { text: 'Solved bonus edge case correctly',           variant: 'good' },
  { text: 'No copy() on df — mutation bug risk',        variant: 'bad'  },
];

const SKILL_COMPARE = [
  { name: 'Python',          claimed: 90, actual: 72, color: 'var(--green)' },
  { name: 'DSA / C++',      claimed: 85, actual: 55, color: 'var(--amber)' },
  { name: 'JavaScript',     claimed: 70, actual: 68, color: 'var(--green)' },
  { name: 'Machine Learning',claimed: 75, actual: 42, color: 'var(--red)'   },
];

const LEARNING_PATH = [
  {
    num: '01',
    title: 'Dynamic programming — 2 weeks',
    desc: 'Focus: memoization, tabulation, classic DP patterns. Target: LeetCode medium DP in under 20 min.',
  },
  {
    num: '02',
    title: 'ML model internals — 3 weeks',
    desc: 'Go beyond preprocessing. Understand how classifiers actually learn: gradient descent, loss functions, regularization.',
  },
  {
    num: '03',
    title: 'Retake in 30 days',
    desc: 'Skill decay tracker will re-challenge you on DSA and ML. Aim for 70+ in both before your next SDE application cycle.',
  },
];

const HM_DATA = [1, 2, 1, 8, 5, 3, 4, 7, 2, 1, 6, 4, 3, 2, 1, 3, 9, 4, 2, 1];

function Heatmap() {
  const max = Math.max(...HM_DATA);
  return (
    <div className="flex gap-1 items-end" style={{ height: 60 }}>
      {HM_DATA.map((v, i) => {
        const pct = v / max;
        const r = Math.round(255 * pct);
        const g = Math.round(200 * (1 - pct));
        return (
          <div
            key={i}
            className="flex-1 rounded-t-sm transition-opacity duration-200 cursor-pointer"
            style={{
              height: Math.max(8, pct * 60),
              background: `rgb(${r},${g},90)`,
            }}
            title={`Line ${i + 1}: ${v} rewrites`}
          />
        );
      })}
    </div>
  );
}

function MetricBar({ metric }) {
  return (
    <div className="flex items-center gap-3 mb-2">
      <span className="text-xs flex-shrink-0" style={{ color: 'var(--muted)', width: 130 }}>
        {metric.name}
      </span>
      <div className="flex-1 h-1 rounded-full" style={{ background: 'var(--border)' }}>
        <div
          className="h-full rounded-full transition-all duration-700"
          style={{ width: `${metric.val}%`, background: metric.color }}
        />
      </div>
      <span className="text-xs font-mono w-6 text-right" style={{ color: metric.color }}>
        {metric.val}
      </span>
    </div>
  );
}

function Scorecard({ skill, onRestart }) {
  const handleDownload = () => {
    const content = `SKILL MIRROR — VERIFIED SCORECARD
================================
Skill tested: ${skill?.label || 'Python + Pandas'}
Execution score: 72/100
Impostor score: 31/100
Peer percentile: 63rd

AI VERDICT:
High confidence claims + slow hesitation on label mapping + 2 external lookups = elevated impostor signal.
Your Python execution is real. Your DSA and ML depth are not.

Generated by Skill Mirror — skillmirror.ai
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'skill-mirror-scorecard.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ maxWidth: 860, margin: '0 auto', padding: '3rem 2rem' }}>
      <StepHeader
        step="STEP 04 — REALITY CHECK DASHBOARD"
        title="The mirror doesn't lie."
        subtitle="All skills tested. All gaps exposed. This is what you actually are — not what your resume says."
      />

      {/* Top 3 metrics */}
      <div className="grid grid-cols-3 gap-3 mb-5">
        {[
          { num: '72',   label: 'execution score', color: 'var(--purple)' },
          { num: '31',   label: 'impostor score',  color: 'var(--amber)'  },
          { num: '63rd', label: 'peer percentile', color: 'var(--green)'  },
        ].map((m) => (
          <Card key={m.label} className="p-5 text-center">
            <div
              className="text-4xl font-black"
              style={{ color: m.color, letterSpacing: '-2px' }}
            >
              {m.num}
            </div>
            <div className="text-xs font-mono mt-1" style={{ color: 'var(--muted)' }}>
              {m.label}
            </div>
          </Card>
        ))}
      </div>

      {/* Impostor banner */}
      <div
        className="flex flex-wrap gap-6 items-center p-6 rounded-xl mb-5"
        style={{
          background: 'linear-gradient(135deg,rgba(255,90,90,0.031),rgba(124,109,248,0.031))',
          border: '0.5px solid var(--border2)',
        }}
      >
        <div
          className="font-black"
          style={{ fontSize: '3.5rem', letterSpacing: '-3px', color: 'var(--amber)', lineHeight: 1 }}
        >
          31
        </div>
        <div className="flex-1" style={{ minWidth: 240 }}>
          <h3 className="text-sm font-black mb-1">Impostor index: moderate</h3>
          <p className="text-xs leading-relaxed" style={{ color: 'var(--muted)', maxWidth: 440 }}>
            High confidence claims + slow hesitation on label mapping + 2 external lookups = elevated
            impostor signal. Your Python execution is real. Your DSA and ML depth are not.
          </p>
          <div className="flex gap-3 mt-4 flex-wrap">
            <button
              onClick={handleDownload}
              className="px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all duration-200 cursor-pointer"
              style={{
                border: '0.5px solid var(--green)',
                background: 'var(--green-dim)',
                color: 'var(--green)',
                fontFamily: 'var(--font)',
              }}
            >
              ↓ Download skill card
            </button>
            <button
              className="px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all duration-200 cursor-pointer"
              style={{
                border: '0.5px solid var(--blue)',
                background: 'rgba(74,158,255,0.063)',
                color: 'var(--blue)',
                fontFamily: 'var(--font)',
              }}
            >
              ↗ Share verified scorecard
            </button>
          </div>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-2 mb-5">
        {/* AI Evaluation breakdown */}
        <Card className="p-5">
          <div
            className="text-xs font-mono tracking-widest mb-4"
            style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
          >
            AI EVALUATION BREAKDOWN
          </div>
          {EVAL_METRICS.map((m) => (
            <MetricBar key={m.name} metric={m} />
          ))}
        </Card>

        {/* Verbal justification */}
        <Card className="p-5">
          <div
            className="text-xs font-mono tracking-widest mb-3"
            style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
          >
            VERBAL JUSTIFICATION ROUND
          </div>
          <p className="text-xs leading-relaxed mb-3" style={{ color: 'var(--muted)' }}>
            AI asks 2–3 follow-up questions to test if you understand what you wrote.
          </p>
          <div
            className="p-3 rounded-lg text-xs font-mono leading-relaxed mb-3"
            style={{ background: 'var(--surface)', border: '0.5px solid var(--border)', color: 'var(--muted)' }}
          >
            <div className="mb-1.5" style={{ color: 'var(--purple)' }}>AI ›</div>
            Why did you use <code style={{ background: 'rgba(255,255,255,0.063)', padding: '1px 4px', borderRadius: 3 }}>.str.lower()</code>{' '}
            before <code style={{ background: 'rgba(255,255,255,0.063)', padding: '1px 4px', borderRadius: 3 }}>.map()</code>?
            What happens if a label is{' '}
            <code style={{ background: 'rgba(255,255,255,0.063)', padding: '1px 4px', borderRadius: 3 }}>NaN</code>?
          </div>
          <div className="flex gap-2 flex-wrap">
            <span
              className="text-xs font-mono px-2 py-1 rounded"
              style={{ border: '0.5px solid var(--border)', color: 'var(--muted)' }}
            >
              Answered correctly: 1/3
            </span>
            <span
              className="text-xs font-mono px-2 py-1 rounded"
              style={{ border: '0.5px solid var(--amber)', color: 'var(--amber)' }}
            >
              Partial understanding
            </span>
          </div>
        </Card>
      </div>

      {/* Behaviour flags */}
      <Card className="p-5 mb-5">
        <div
          className="text-xs font-mono tracking-widest mb-3"
          style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
        >
          BEHAVIOUR FLAGS
        </div>
        <div className="flex flex-wrap gap-2">
          {BEHAVIOUR_FLAGS.map((f) => (
            <Flag key={f.text} variant={f.variant}>
              {f.text}
            </Flag>
          ))}
        </div>
      </Card>

      {/* Frustration heatmap */}
      <Card className="p-5 mb-5">
        <div
          className="text-xs font-mono tracking-widest mb-3"
          style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
        >
          FRUSTRATION HEATMAP — rewrites per line
        </div>
        <Heatmap />
      </Card>

      {/* Illusion vs reality */}
      <Card className="p-5 mb-5">
        <div
          className="text-xs font-mono tracking-widest mb-5"
          style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
        >
          ILLUSION VS REALITY — PER SKILL
        </div>
        <div className="flex flex-col gap-5">
          {SKILL_COMPARE.map((sc) => (
            <div key={sc.name}>
              <div className="text-xs font-bold mb-2">{sc.name}</div>
              <div className="flex flex-col gap-1.5">
                <SkillBar label="claimed" value={sc.claimed} color="rgba(124,109,248,0.7)" />
                <SkillBar label="actual"  value={sc.actual}  color={sc.color} />
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Gap cards */}
      <div className="flex flex-col gap-3 mb-5">
        <div
          className="p-5 rounded-xl"
          style={{ background: 'rgba(245,166,35,0.031)', border: '0.5px solid var(--amber)' }}
        >
          <h4 className="text-xs font-bold mb-2" style={{ color: 'var(--amber)' }}>
            Biggest illusion gap: DSA in C++
          </h4>
          <p className="text-xs leading-relaxed" style={{ color: 'var(--muted)' }}>
            You listed DSA as a core strength under "CS Fundamentals" but scored 55/100 — 30 points
            below your implied claim. You solved basic traversal but broke down on dynamic programming.
            This is your #1 gap to close before any SDE interview.
          </p>
        </div>
        <div
          className="p-5 rounded-xl"
          style={{ background: 'rgba(255,90,90,0.031)', border: '0.5px solid var(--red)' }}
        >
          <h4 className="text-xs font-bold mb-2" style={{ color: 'var(--red)' }}>
            Machine learning: group project ≠ personal skill
          </h4>
          <p className="text-xs leading-relaxed" style={{ color: 'var(--muted)' }}>
            Your ML score of 42 suggests you understand the pipeline surface-level but lack depth.
            The fraud detection project was collaborative — the system flagged that your preprocessing
            knowledge is real but model architecture understanding is shallow.
          </p>
        </div>
      </div>

      {/* Learning path */}
      <Card className="p-5 mb-8">
        <div
          className="text-xs font-mono tracking-widest mb-5"
          style={{ color: 'var(--dim)', letterSpacing: '0.12em' }}
        >
          AI-GENERATED LEARNING PATH
        </div>
        <div className="flex flex-col gap-5">
          {LEARNING_PATH.map((item) => (
            <div key={item.num} className="flex gap-3 items-start">
              <div
                className="flex-shrink-0 flex items-center justify-center rounded-lg text-xs font-mono font-bold"
                style={{
                  width: 28,
                  height: 28,
                  background: 'var(--purple-dim)',
                  border: '0.5px solid var(--purple)',
                  color: 'var(--purple)',
                }}
              >
                {item.num}
              </div>
              <div>
                <h5 className="text-xs font-bold mb-1">{item.title}</h5>
                <p className="text-xs leading-relaxed" style={{ color: 'var(--muted)' }}>
                  {item.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Restart */}
      <div className="flex justify-center">
        <BtnGhost onClick={onRestart}>← Audit another resume</BtnGhost>
      </div>
    </div>
  );
}

export default Scorecard;
